### ISSUE TITLE
when trying to add reset all button to work with dc charts, the reset all button not work with dc.leaflet map.

### ISSUE THREAD

**Issue by lipingyang-geoai** [yurukov/dc.leaflet.js#11]
Hello, dc.leaflet.js community, when I am trying to add reset all button to work with dc charts, the reset all button not work with dc.leaflet map. any suggestions to make this work?

**Comment by gordonwoodhull** [comment]
This project is the original dc.leaflet.js; the fork [dc-js/dc.leaflet.js](https://github.com/dc-js/dc.leaflet.js) is somewhat more recent.

This issue dc-js/dc.leaflet.js#42 indicates that 

```js
dc.filterAll(); dc.redrawAll();
```

 should work?

**Comment by lipingyang-geoai** [comment]
@gordonwoodhull Thank you Gordon! this works.

**Comment by gordonwoodhull** [comment]
Great! Please close the issue.
